version: '3'
services:
  clouddriver:
    container_name: clouddriver
    env_file: ./compose.env
    environment:
      - AWS_ACCESS_KEY_ID
      - AWS_SECRET_ACCESS_KEY
      - "SERVICES_FRONT50_BASEURL=http://$DOCKER_IP:8080"
    image: quay.io/spinnaker/clouddriver:master
    depends_on:
      - redis
    ports:
      - "7002:7002"
  deck:
    container_name: deck
    # Changing the run command to update settings.js
    build:
      context: .
      dockerfile: Dockerfile-deck
    environment:
      - "API_HOST=http://gate:8084"
      - DECK_HOST=0.0.0.0
      - DECK_PORT=9000
      - PROTOCOL=http
      - AUTH_ENABLED=false
      - "AUTH_ENDPOINT=http://$DOCKER_IP:8084/auth/user"
    ports:
      - "9000:9000"
    depends_on:
      - gate
  echo:
    container_name: echo
    env_file: ./compose.env
    environment:
      - "JAVA_OPTS=-javaagent:/opt/echo/lib/jamm-0.2.5.jar"
    image: quay.io/spinnaker/echo:master
    ports:
      - "8089:8089"
    depends_on:
      - front50
  front50:
    container_name: front50
    env_file: ./compose.env
    environment:
      - "JAVA_OPTS=-javaagent:/opt/front50/lib/jamm-0.2.5.jar"
    image: quay.io/spinnaker/front50:master
    ports:
      - "8080:8080"
  gate:
    container_name: gate
    env_file: ./compose.env
    image: quay.io/spinnaker/gate:master
    depends_on:
      - redis
      - clouddriver
      - echo
      - front50
      - igor
      - orca
      - rosco
    ports:
      - "8084:8084"
    depends_on:
      - clouddriver
      - front50
  igor:
    container_name: igor
    env_file: ./compose.env
    image: quay.io/spinnaker/igor:master
    depends_on:
      - redis
      - clouddriver
      - echo
    ports:
      - "8088:8088"
  orca:
    container_name: orca
    env_file: ./compose.env
    image: quay.io/spinnaker/orca:master
    depends_on:
      - redis
      - clouddriver
      - echo
      - front50
      - igor
      - rosco
    ports:
      - "8083:8083"
  redis:
    command: "redis-server --appendonly yes"
    container_name: redis
    ports:
      - "6379:6379"
    image: redis
  rosco:
    container_name: rosco
    env_file: ./compose.env
    image: quay.io/spinnaker/rosco:master
    depends_on:
      - redis
    ports:
      - "8087:8087"
  fiat:
    container_name: fiat
    env_file: ./compose.env
    image: quay.io/spinnaker/fiat:master
    depends_on:
      - redis
      - clouddriver
      - front50
    ports:
      - "7003:7003"
